language: node_js

node_js:
  - "10.7.0"

cache:
  directories:
    - node_modules

script:
  - yarn
  - yarn test

deploy:
  provider: npm
  email: matthew.suhay@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
  skip_cleanup: true

notifications:
  email:
    on_success: never
    on_failure: always
